version: '3.9'
services:
  myapi: 
    build: .
    ports:
      - "4000:4000"
    networks:
      - mynet
    depends_on:
      - myredis
  myredis:
    image: redis:latest
    networks:
      - mynet

networks:
  mynet: