name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Flask API Docker image
      run: |
        docker build -t justinkhulsey/project-12 . 
          
    - name: Launch the service using docker-compose 
      env:
        SLACK_URL: ${{ secrets.SLACK_URL_DEV }}
      run: |
        docker compose up -d 
    - name: Verify that the correct containers are running 
      run: docker ps 
      
    - name: Run API Test
      run: |
        pip install flask
        python test.py --port 4000 --host localhost
    - name: Build & Push the Docker image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "justinkhulsey" --password-stdin
        docker image build -t justinkhulsey/project-12:latest .
        docker push justinkhulsey/project-12:latest